FROM mysql
ENV MYSQL_ROOT_PASSWORD bruno
#após fazer isso va até o terminal e execute
#docker build -t mysql-image(nome que você quiser criar) -f api/db/Dockerfile .

#depois de criar o arquivo sql volte ao terminal e execute o seguinte comando
#docker exec -i mysql-container mysql -uroot -bruno < api/db/script.sql

#após esse comando ele cria o banco de dados, as tabelas e os valores
#digite o comando docker exec -it mysql-container /bin/bsah (esse bin/bash significa que ira utilizar o terminal)

#mysql -uroot -bruno
#use bruno; você vai acessar o banco
#select * from products; vai acessar a tabela

